# Generated by Django 6.0.8 on 2026-10-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='judge_mode',
            field=models.CharField(choices=[('query', '查询结果'), ('schema', '表结构')], default='query', max_length=10, verbose_name='判题模式'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='expected_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testcase',
            name='probes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(blank=True, default=''),
        ),
    ]
