# Generated by Django 6.0.8 on 2026-10-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_judge_mode_testcase_expected_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='judge_compare_names',
            field=models.BooleanField(default=False, verbose_name='比对约束/索引名称'),
        ),
        migrations.AddField(
            model_name='question',
            name='judge_strictness',
            field=models.CharField(choices=[('subset', '宽松：多出的列/约束/索引不判错'), ('exact', '严格：对象集合必须与期望一致')], default='subset', max_length=10, verbose_name='结构严格度'),
        ),
    ]
