"""
Django settings for sql_oj project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

import pymysql
pymysql.install_as_MySQLdb()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 环境变量读取辅助：便于容器化/多环境部署，未设置时回退到内置默认值
def env_str(key: str, default: str) -> str:
    """读取字符串环境变量，缺失或为空时返回默认值。"""
    value = os.environ.get(key)
    return default if value is None or value == "" else value


def env_bool(key: str, default: bool) -> bool:
    """读取布尔环境变量，识别 1/true/yes/on（大小写不敏感）。"""
    value = os.environ.get(key)
    if value is None or value == "":
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 可通过环境变量 DJANGO_SECRET_KEY 覆盖（容器化部署时建议显式设置）
SECRET_KEY = env_str(
    'DJANGO_SECRET_KEY',
    'django-insecure-p!mb461@nlo-$dq@66qheq#ppzjvqgibs_03oh_u4i=d_o07wa',
)

# SECURITY WARNING: don't run with debug turned on in production!
# 可通过环境变量 DJANGO_DEBUG 覆盖（如 DJANGO_DEBUG=False）
DEBUG = env_bool('DJANGO_DEBUG', True)

# 逗号分隔的主机列表；容器内前端 Nginx 以服务名 backend 访问，故默认放行所有主机
ALLOWED_HOSTS = [
    host.strip()
    for host in env_str('DJANGO_ALLOWED_HOSTS', '*').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 第三方库
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    # 自定义应用
    'apps.users',
    'apps.questions',
    'apps.exams',
    'apps.submissions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS 必须放在 CommonMiddleware 前面
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sql_oj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sql_oj.wsgi.application'

ASGI_APPLICATION = 'sql_oj.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 连接参数均可通过环境变量覆盖（容器化部署时指向 mysql 服务）
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env_str('MYSQL_DATABASE', 'sql_oj_db'),
        'USER': env_str('MYSQL_USER', 'root'),
        'PASSWORD': env_str('MYSQL_PASSWORD', 'sql_oj'),
        'HOST': env_str('MYSQL_HOST', 'localhost'),
        'PORT': env_str('MYSQL_PORT', '3306'),
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ========== DRF + JWT + CORS 配置 ==========
from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

CORS_ALLOW_ALL_ORIGINS = True  # 开发阶段全开

AUTH_USER_MODEL = 'users.User'  # 使用自定义用户模型
